apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-foundations
  namespace: argocd-exercise
  annotations:
    # --- ADD THIS ANNOTATION FOR CIRCLECI ---
    circleci.com/project-id: $CIRCLE_PROJECT_ID #fe84c594-4a8f-4e9f-b6ac-92f69b4b9165
  labels:
    app: gitops-foundations
    # --- ADD/ADJUST THESE LABELS FOR CIRCLECI ---
    circleci.com/component-name: gitops-foundations 
    circleci.com/version: 2.0.1                     # Match your app's version

spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-foundations
  template:
    metadata:
      labels:
        app: gitops-foundations
        # --- ADD THESE LABELS FOR CIRCLECI (POD TEMPLATE) ---
        circleci.com/component-name: gitops-foundations
        circleci.com/version: 2.0.1
    spec:
      containers:
      - name: gitops-foundations
        image: soravitwetprasit/gitops-foundations:3.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 2
